openapi: 3.0.3
info:
  title: Milkyway.Core.ServiceEnablement.APIs
  description: APIs for management connectivity
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/CHANAKMEM/Milkyway.Core.ServiceEnablement.APIs/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- Bearer: []
paths:
  /api/v2/project/{projectId}/connectivities/suspend:
    post:
      tags:
      - Connectivities
      summary: Suspend SIM connectivity
      description: ระงับการใช้งานของ SIM หนึ่งหรือหลายรายการ
      operationId: suspendConnectivity
      parameters:
      - name: projectId
        in: path
        description: รหัสโปรเจกต์
        required: true
        schema:
          type: string
      - name: x-ais-order-ref
        in: header
        required: true
        schema:
          type: string
      - name: x-ais-channel
        in: header
        required: true
        schema:
          type: string
      - name: x-ais-username
        in: header
        required: true
        schema:
          type: string
      - name: x-ais-user-id
        in: header
        required: true
        schema:
          type: string
      - name: content-language
        in: header
        required: false
        schema:
          type: string
          default: en
      - name: x-access-token
        in: header
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              minItems: 1
              type: array
              items:
                $ref: "#/components/schemas/connectivities_suspend_body"
          text/csv:
            schema:
              type: string
              format: binary
            examples:
              example1:
                summary: Example CSV Input
                value: |
                  mobileNo,simSerial,taxId
                  0829921384,2430004100504,678123421111401
                  0829921385,2430004100505,678123421111402
        required: true
      responses:
        "200":
          description: การร้องขอสำเร็จ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/inline_response_200"
            text/csv:
              schema:
                type: string
                format: binary
              examples:
                success:
                  summary: Example CSV Response
                  value: |
                    mobileNo,simSerial,taxId,mobileStatus,code,message
                    0829921384,2430004100504,678123421111401,Suspend-Inprogress,20200,The requested operation now in progress.
                    0829921385,2430004100505,678123421111402,Suspend-Inprogress,20200,The requested operation now in progress.
        "400":
          description: ข้อมูลไม่ถูกต้อง
        "401":
          description: ไม่มีสิทธิ์เข้าถึง (Unauthorized)
        "500":
          description: Internal server error
  /api/v2/project/{projectId}/connectivities/reconnect:
    post:
      tags:
      - Connectivities
      summary: Reconnect SIM connectivity
      description: เปิดการใช้งาน SIM หนึ่งหรือหลายรายการอีกครั้ง
      operationId: reconnectConnectivity
      parameters:
      - name: projectId
        in: path
        description: รหัสโปรเจกต์
        required: true
        schema:
          type: string
      - name: x-ais-order-ref
        in: header
        required: true
        schema:
          type: string
      - name: x-ais-channel
        in: header
        required: true
        schema:
          type: string
      - name: x-ais-username
        in: header
        required: true
        schema:
          type: string
      - name: x-ais-user-id
        in: header
        required: true
        schema:
          type: string
      - name: content-language
        in: header
        required: false
        schema:
          type: string
          default: en
      - name: x-access-token
        in: header
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              minItems: 1
              type: array
              items:
                $ref: "#/components/schemas/connectivities_reconnect_body"
          text/csv:
            schema:
              type: string
              format: binary
            examples:
              example1:
                summary: Example CSV Input
                value: |
                  mobileNo,simSerial,taxId,mainPackageName,mainPackageCode
                  0829921384,2430004100504,678123421111401,Smartway Fleet Management APN 60B FixIP Corp,P1609408189
        required: true
      responses:
        "200":
          description: การร้องขอสำเร็จ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/inline_response_200_1"
            text/csv:
              schema:
                type: string
                format: binary
              examples:
                success:
                  summary: Example CSV Response
                  value: |
                    mobileNo,simSerial,taxId,mobileStatus,code,message
                    0829921384,2430004100504,678123421111401,Activate-Inprogress,20200,The requested operation now in progress.
        "400":
          description: ข้อมูลไม่ถูกต้อง
        "401":
          description: ไม่มีสิทธิ์เข้าถึง (Unauthorized)
        "500":
          description: Internal server error
  /api/v2/project/{projectId}/connectivities/terminates:
    post:
      tags:
      - Connectivities
      summary: Terminate SIM connectivity
      description: ยกเลิกการใช้งานของ SIM หนึ่งหรือหลายรายการ
      operationId: terminateConnectivity
      parameters:
      - name: projectId
        in: path
        required: true
        schema:
          type: string
      - name: x-ais-order-ref
        in: header
        required: true
        schema:
          type: string
      - name: x-ais-channel
        in: header
        required: true
        schema:
          type: string
      - name: content-language
        in: header
        required: false
        schema:
          type: string
          default: en
      - name: content-type
        in: header
        required: false
        schema:
          type: string
          default: application/json
      - name: accept
        in: header
        required: true
        schema:
          type: string
          default: application/json
      - name: authorization
        in: header
        required: true
        schema:
          type: string
      - name: mw-user-id
        in: header
        required: false
        schema:
          type: string
      - name: mw-user-name
        in: header
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              minItems: 1
              type: array
              items:
                $ref: "#/components/schemas/connectivities_suspend_body"
          text/csv:
            schema:
              type: string
              format: binary
            examples:
              example1:
                summary: Example CSV Input
                value: |
                  mobileNo,simSerial,taxId
                  0829921384,2430004100504,678123421111401
                  0829921385,2430004100505,678123421111402
        required: true
      responses:
        "200":
          description: การร้องขอสำเร็จ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/inline_response_200_2"
            text/csv:
              schema:
                type: string
                format: binary
              examples:
                success:
                  summary: Example CSV Response
                  value: |
                    mobileNo,simSerial,taxId,mobileStatus,code,message
                    0829921384,2430004100504,678123421111401,Terminate-Inprogress,20200,The requested operation now in progress.
                    0829921385,2430004100505,678123421111402,Terminate-Inprogress,20200,The requested operation now in progress.
        "400":
          description: ข้อมูลไม่ถูกต้อง
        "401":
          description: ไม่มีสิทธิ์เข้าถึง (Unauthorized)
        "500":
          description: Internal server error
components:
  schemas:
    connectivities_reconnect_body:
      type: object
      properties:
        mobileNo:
          type: string
          example: "0829921384"
        simSerial:
          type: string
          example: "2430004100504"
        taxId:
          type: string
          example: "678123421111401"
        mainPackageName:
          type: string
          example: Smartway Fleet Management APN 60B FixIP Corp
    connectivities_suspend_body:
      type: object
      properties:
        mobileNo:
          type: string
          example: "0829921384"
        simSerial:
          type: string
          example: "2430004100504"
        taxId:
          type: string
          example: "678123421111401"
    inline_response_200_1:
      type: object
      properties:
        mobileNo:
          type: string
          example: "0829921384"
        simSerial:
          type: string
          example: "2430004100504"
        taxId:
          type: string
          example: "678123421111401"
        mobileStatus:
          type: string
          example: Activate-Inprogress
        code:
          type: string
          example: "20200"
        message:
          type: string
          example: The requested operation now in progress.
    inline_response_200:
      type: object
      properties:
        mobileNo:
          type: string
          example: "0829921384"
        simSerial:
          type: string
          example: "2430004100504"
        taxId:
          type: string
          example: "678123421111401"
        mobileStatus:
          type: string
          example: Suspend-Inprogress
        code:
          type: string
          example: "20200"
        message:
          type: string
          example: The requested operation now in progress.
    inline_response_200_2:
      type: object
      properties:
        mobileNo:
          type: string
          example: "0829921384"
        simSerial:
          type: string
          example: "2430004100504"
        taxId:
          type: string
          example: "678123421111401"
        mobileStatus:
          type: string
          example: Terminate-Inprogress
        code:
          type: string
          example: "20200"
        message:
          type: string
          example: The requested operation now in progress.
  securitySchemes:
    oauth2:
      type: oauth2
      description: |
        The Client Credentials grant type is used by clients to obtain an access token outside of the context of a user.
      flows:
        clientCredentials:
          tokenUrl: http://10.138.37.218:31351/connect/token
          scopes: {}
    Bearer:
      type: apiKey
      description: |
        JWT Authorization header using the Bearer scheme.
        Enter 'Bearer' [space] and then your token in the text input below.
        Example: "Bearer 12345abcdef"
      name: Authorization
      in: header
