openapi: 3.0.3
info:
  title: Milkyway.Core.ServiceEnablement.APIs
  version: 1.0.0
  description: APIs for management connectivity + SKY callbacks

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://IP:PORT/Milkyway.Core.ServiceEnablement.APIs/1.0.0

security:
  - Bearer: []

tags:
  - name: Connectivities
    description: Connectivity management APIs
  - name: SKY-IOT Callback
    description: SKY-IOT -> Milkyway callbacks
  - name: SKY-MPO Callback
    description: SKY-MPO -> Milkyway callbacks

paths:
  # =========================
  # CONNECTIVITIES (partial - from your file)
  # =========================
  /api/v2/project/{projectId}/connectivities/suspend:
    post:
      summary: Suspend SIM connectivity
      description: ระงับการใช้งานของ SIM หนึ่งหรือหลายรายการ
      operationId: suspendConnectivity
      tags: [Connectivities]
      parameters:
        - name: projectId
          in: path
          required: true
          schema: { type: string }
          description: Project ID
        - $ref: "#/components/parameters/XAisOrderRef"
        - name: x-ais-channel
          in: header
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  mobileNo: { type: string, example: "0829921384" }
                  simSerial: { type: string, example: "2430004100504" }
                  taxId: { type: string, example: "678123421111401" }
      responses:
        "200": { description: การร้องขอสำเร็จ }
        "400": { description: ข้อมูลไม่ถูกต้อง }
        "401": { description: ไม่มีสิทธิ์เข้าถึง (Unauthorized) }
        "500": { description: Internal server error }

  /api/v2/project/{projectId}/connectivities/reconnect:
    post:
      summary: Reconnect SIM connectivity
      operationId: reconnectConnectivity
      tags: [Connectivities]
      parameters:
        - name: projectId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/XAisOrderRef"
        - name: x-ais-channel
          in: header
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  mobileNo: { type: string }
                  simSerial: { type: string }
                  taxId: { type: string }
                  mainPackageName: { type: string }
      responses:
        "200": { description: การร้องขอสำเร็จ }
        "400": { description: ข้อมูลไม่ถูกต้อง }
        "401": { description: ไม่มีสิทธิ์เข้าถึง (Unauthorized) }
        "500": { description: Internal server error }

  /api/v2/project/{projectId}/connectivities/terminates:
    post:
      summary: Terminate SIM connectivity
      operationId: terminateConnectivity
      tags: [Connectivities]
      parameters:
        - name: projectId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/XAisOrderRef"
        - name: x-ais-channel
          in: header
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  mobileNo: { type: string }
                  simSerial: { type: string }
                  taxId: { type: string }
      responses:
        "200": { description: การร้องขอสำเร็จ }
        "400": { description: ข้อมูลไม่ถูกต้อง }
        "401": { description: ไม่มีสิทธิ์เข้าถึง (Unauthorized) }
        "500": { description: Internal server error }

  /api/v2/project/{projectId}/connectivities/change-sim:
    post:
      summary: Change SIM Serial in bulk
      operationId: changeSimBulk
      tags: [Connectivities]
      parameters:
        - name: projectId
          in: path
          required: true
          schema: { type: string }
        - $ref: "#/components/parameters/XAisOrderRef"
        - name: x-ais-channel
          in: header
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  mobileNo: { type: string }
                  oldSimSerial: { type: string }
                  newSimSerial: { type: string }
                  taxId: { type: string }
      responses:
        "200": { description: การร้องขอสำเร็จ }
        "400": { description: Invalid request body }
        "401": { description: Unauthorized }
        "403": { description: Forbidden }
        "404": { description: Not Found }
        "500": { description: Internal Server Error }

  # ==========================================================
  # SKY-IOT CALLBACKS (ALL ACTIONS use Ack body) + type query param
  # ==========================================================
  /api/v1/sky-iot/callback/register-sim:
    post:
      tags: [SKY-IOT Callback]
      summary: SKY-IOT Callback - Register SIM
      operationId: skyIotCallbackRegisterSim
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyIotAckCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-iot/callback/change-main-package:
    post:
      tags: [SKY-IOT Callback]
      summary: SKY-IOT Callback - Change Main Package
      operationId: skyIotCallbackChangeMainPackage
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyIotAckCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-iot/callback/purchase-on-top:
    post:
      tags: [SKY-IOT Callback]
      summary: SKY-IOT Callback - Purchase On-top Package
      operationId: skyIotCallbackPurchaseOnTop
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyIotAckCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-iot/callback/change-sim:
    post:
      tags: [SKY-IOT Callback]
      summary: SKY-IOT Callback - Change SIM
      operationId: skyIotCallbackChangeSim
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyIotAckCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-iot/callback/suspend:
    post:
      tags: [SKY-IOT Callback]
      summary: SKY-IOT Callback - Suspend SIM
      operationId: skyIotCallbackSuspend
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyIotAckCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-iot/callback/activate:
    post:
      tags: [SKY-IOT Callback]
      summary: SKY-IOT Callback - Activate SIM
      operationId: skyIotCallbackActivate
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyIotAckCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-iot/callback/terminate:
    post:
      tags: [SKY-IOT Callback]
      summary: SKY-IOT Callback - Terminate SIM
      operationId: skyIotCallbackTerminate
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyIotAckCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  # ==========================================================
  # SKY-MPO CALLBACKS + type query param
  # ==========================================================
  /api/v1/sky-mpo/callback/register-sim:
    post:
      tags: [SKY-MPO Callback]
      summary: SKY-MPO Callback - Register SIM
      operationId: skyMpoCallbackRegisterSim
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyMpoRegisterSimRichCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-mpo/callback/change-main-package:
    post:
      tags: [SKY-MPO Callback]
      summary: SKY-MPO Callback - Change Main Package
      operationId: skyMpoCallbackChangeMainPackage
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyMpoChangeProductCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-mpo/callback/purchase-on-top:
    post:
      tags: [SKY-MPO Callback]
      summary: SKY-MPO Callback - Purchase On-top Package
      operationId: skyMpoCallbackPurchaseOnTop
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyMpoChangeProductCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-mpo/callback/change-sim:
    post:
      tags: [SKY-MPO Callback]
      summary: SKY-MPO Callback - Change SIM
      operationId: skyMpoCallbackChangeSim
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyMpoStateCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-mpo/callback/suspend:
    post:
      tags: [SKY-MPO Callback]
      summary: SKY-MPO Callback - Suspend
      operationId: skyMpoCallbackSuspend
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyMpoStateCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-mpo/callback/activate:
    post:
      tags: [SKY-MPO Callback]
      summary: SKY-MPO Callback - Activate
      operationId: skyMpoCallbackActivate
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyMpoStateCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

  /api/v1/sky-mpo/callback/terminate:
    post:
      tags: [SKY-MPO Callback]
      summary: SKY-MPO Callback - Terminate
      operationId: skyMpoCallbackTerminate
      parameters:
        - $ref: "#/components/parameters/XAisOrderRef"
        - $ref: "#/components/parameters/CallbackType"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SkyMpoTerminateCallback" }
      responses:
        "200": { $ref: "#/components/responses/CallbackAccepted" }
        "400": { $ref: "#/components/responses/BadRequest" }

components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: Client Credentials grant type
      flows:
        clientCredentials:
          tokenUrl: http://10.138.37.218:31351/connect/token
          scopes: {}
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: JWT Authorization header using the Bearer scheme.

  parameters:
    XAisOrderRef:
      name: x-ais-OrderRef
      in: header
      required: true
      description: Reference/Idempotency key for this request (should match original request reference)
      schema:
        type: string
        maxLength: 128
        example: CO-vvz2s-23090510404825656900

    CallbackType:
      name: type
      in: query
      required: true
      description: |
        Callback processing type:
        - mobile: single billing per number (ลงทะเบียนและเปิดบิลเบอร์ใครเบอร์มัน)
        - sa: shared billing under the same billing account (Service Account mode)
        - ba: shared billing under the same billing account (Billing Account mode)
      schema:
        type: string
        enum: [mobile, sa, ba]
      example: mobile

  schemas:
    CallbackAck:
      type: object
      required: [code, message]
      properties:
        code: { type: string, example: "200" }
        message: { type: string, example: "Callback received successfully" }

    ErrorResponse:
      type: object
      required: [resultCode, message]
      properties:
        resultCode: { type: string, example: "40000" }
        message: { type: string, example: "Invalid payload" }

    SkyIotAckCallback:
      type: object
      additionalProperties: true
      required: [publicIdType, publicIdValue, privateIdType, privateIdValue, orderNo, statusCode]
      properties:
        publicIdType: { type: string, example: "iotNo" }
        publicIdValue: { type: string, example: "9991201036" }
        privateIdType: { type: string, example: "conductorRefId" }
        privateIdValue: { type: string, example: "4fa7d16d-b3c6-4783-957a-bc34d78d7459" }
        orderNo: { type: string, example: "IC-NEW-25050615115260419993" }
        statusCode: { type: string, example: "200" }

    SkyMpoRegisterSimRichCallback:
      type: object
      additionalProperties: true
      required: [privateIdType, privateIdValue, publicIdType, publicIdValue, orderRefId, statusCode, state, stateDate]
      properties:
        privateIdType: { type: string, example: "uuid" }
        privateIdValue: { type: string, example: "ec821f7d-f2b8-4ddf-97af-3fa19311ac51" }
        publicIdType: { type: string, example: "mobileNo" }
        publicIdValue: { type: string, example: "0893647975" }
        orderRefId: { type: string, example: "CO-vvz2s-23090510404825656900" }
        statusCode: { type: string, example: "200" }
        state: { type: string, example: "Completed" }
        stateDate: { type: string, example: "05/09/2023 10:41:46" }

    SkyMpoChangeProductCallback:
      type: object
      additionalProperties: true
      required: [publicIdValue, privateIdType, privateIdValue, listOrderItem]
      properties:
        publicIdValue: { type: string, example: "0717000964" }
        privateIdType: { type: string, example: "uuid" }
        privateIdValue: { type: string, example: "43ea9527-82f2-4950-add0-af622775b505" }
        state: { type: string, nullable: true, example: "Completed" }
        State: { type: string, nullable: true, example: "Completed" }
        orderRefId: { type: string, nullable: true, example: "FS-h8z86-230106173656056952239854" }
        "orderRefId ": { type: string, nullable: true, example: "FS-h8z86-230106173656056952239854" }
        listOrderItem:
          type: array
          minItems: 1
          items:
            type: object
            additionalProperties: true

    SkyMpoStateCallback:
      type: object
      additionalProperties: true
      required: [privateIdType, privateIdValue, orderRefId, state, stateDate]
      properties:
        privateIdType: { type: string, example: "uuid" }
        privateIdValue: { type: string, example: "ec821f7d-f2b8-4ddf-97af-3fa19311ac51" }
        orderRefId: { type: string, example: "CO-vvz2s-23090510404825656900" }
        state: { type: string, example: "Completed" }
        stateDate: { type: string, example: "05/09/2023 10:41:46" }

    SkyMpoTerminateCallback:
      type: object
      additionalProperties: true
      required: [privateIdType, privateIdValue, publicIdType, publicIdValue, orderRefId, state, stateDate]
      properties:
        privateIdType: { type: string, example: "uuid" }
        privateIdValue: { type: string, example: "ec821f7d-f2b8-4ddf-97af-3fa19311ac51" }
        publicIdType: { type: string, example: "mobileNo" }
        publicIdValue: { type: string, example: "0893647975" }
        orderRefId: { type: string, example: "CO-vvz2s-23090510404825656900" }
        state: { type: string, example: "Completed" }
        stateDate: { type: string, example: "05/09/2023 10:41:46" }

  responses:
    CallbackAccepted:
      description: Callback accepted
      content:
        application/json:
          schema: { $ref: "#/components/schemas/CallbackAck" }
    BadRequest:
      description: Invalid payload
      content:
        application/json:
          schema: { $ref: "#/components/schemas/ErrorResponse" }
