openapi: 3.0.3
info:
  title: Milkyway.Core.ServiceEnablement.APIs
  version: 1.0.0
  description: APIs for management connectivity

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://IP:PORT/Milkyway.Core.ServiceEnablement.APIs/1.0.0

security:
  - Bearer: []

paths:
  /api/v2/project/{projectId}/connectivities/suspend:
    post:
      summary: Suspend SIM connectivity
      description: ระงับการใช้งานของ SIM หนึ่งหรือหลายรายการ
      operationId: suspendConnectivity
      tags:
        - Connectivities
      parameters:
        - name: projectId
          in: path
          required: true
          schema: { type: string }
          description: Project ID

        - name: x-ais-OrderRef
          in: header
          required: true
          schema: { type: string }
          description: Reference/Idempotency key for this request
        - name: x-ais-channel
          in: header
          required: true
          schema: { type: string }
        - name: content-language
          in: header
          required: false
          schema: { type: string }
          description: Preferred language for messages (e.g., "th", "en")
        - name: mw-user-id
          in: header
          schema: { type: string }
          example: 63e9eb9e733c3cc96dfe5027

        - name: mw-user-name
          in: header
          schema: { type: string }
          example: kanct571

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  mobileNo:
                    type: string
                    example: '0829921384'
                  simSerial:
                    type: string
                    example: '2430004100504'
                  taxId:
                    type: string
                    example: '678123421111401'
          text/csv:
            schema:
              type: string
              format: binary
            examples:
              example1:
                summary: Example CSV Input
                value: |
                  mobileNo,simSerial,taxId
                  0829921384,2430004100504,678123421111401
                  0829921385,2430004100505,678123421111402

      responses:
        '200':
          description: การร้องขอสำเร็จ
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mobileNo:
                      type: string
                      example: '0829921384'
                    simSerial:
                      type: string
                      example: '2430004100504'
                    taxId:
                      type: string
                      example: '678123421111401'
                    mobileStatus:
                      type: string
                      example: Suspend-Inprogress
                    code:
                      type: string
                      example: "20200"
                    message:
                      type: string
                      example: The requested operation now in progress.
            text/csv:
              schema:
                type: string
                format: binary
              examples:
                success:
                  summary: Example CSV Response
                  value: |
                    mobileNo,simSerial,taxId,mobileStatus,code,message
                    0829921384,2430004100504,678123421111401,Suspend-Inprogress,20200,The requested operation now in progress.
                    0829921385,2430004100505,678123421111402,Suspend-Inprogress,20200,The requested operation now in progress.
        '400':
          description: ข้อมูลไม่ถูกต้อง
        '401':
          description: ไม่มีสิทธิ์เข้าถึง (Unauthorized)
        '500':
          description: Internal server error
  /api/v2/project/{projectId}/connectivities/reconnect:
    post:
      summary: Reconnect SIM connectivity
      description: เปิดการใช้งาน SIM หนึ่งหรือหลายรายการอีกครั้ง
      operationId: reconnectConnectivity
      tags:
        - Connectivities
      parameters:
        - name: projectId
          in: path
          required: true
          schema: { type: string }
          description: Project ID

        - name: x-ais-OrderRef
          in: header
          required: true
          schema: { type: string }
          description: Reference/Idempotency key for this request
        - name: x-ais-channel
          in: header
          required: true
          schema: { type: string }
        - name: content-language
          in: header
          required: false
          schema: { type: string }
          description: Preferred language for messages (e.g., "th", "en")
        - name: mw-user-id
          in: header
          schema: { type: string }
          example: 63e9eb9e733c3cc96dfe5027

        - name: mw-user-name
          in: header
          schema: { type: string }
          example: kanct571

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  mobileNo:
                    type: string
                    example: '0829921384'
                  simSerial:
                    type: string
                    example: '2430004100504'
                  taxId:
                    type: string
                    example: '678123421111401'
                  mainPackageName:
                    type: string
                    example: 'Smartway Fleet Management APN 60B FixIP Corp'
                 
          text/csv:
            schema:
              type: string
              format: binary
            examples:
              example1:
                summary: Example CSV Input
                value: |
                  mobileNo,simSerial,taxId,mainPackageName,mainPackageCode
                  0829921384,2430004100504,678123421111401,Smartway Fleet Management APN 60B FixIP Corp,P1609408189

      responses:
        '200':
          description: การร้องขอสำเร็จ
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mobileNo:
                      type: string
                      example: '0829921384'
                    simSerial:
                      type: string
                      example: '2430004100504'
                    taxId:
                      type: string
                      example: '678123421111401'
                    mobileStatus:
                      type: string
                      example: Activate-Inprogress
                    code:
                      type: string
                      example: "20200"
                    message:
                      type: string
                      example: The requested operation now in progress.
            text/csv:
              schema:
                type: string
                format: binary
              examples:
                success:
                  summary: Example CSV Response
                  value: |
                    mobileNo,simSerial,taxId,mobileStatus,code,message
                    0829921384,2430004100504,678123421111401,Activate-Inprogress,20200,The requested operation now in progress.

        '400':
          description: ข้อมูลไม่ถูกต้อง
        '401':
          description: ไม่มีสิทธิ์เข้าถึง (Unauthorized)
        '500':
          description: Internal server error
  /api/v2/project/{projectId}/connectivities/terminates:
    post:
      summary: Terminate SIM connectivity
      description: ยกเลิกการใช้งานของ SIM หนึ่งหรือหลายรายการ
      operationId: terminateConnectivity
      tags:
        - Connectivities
      parameters:
        - name: projectId
          in: path
          required: true
          schema: { type: string }
          description: Project ID

        - name: x-ais-OrderRef
          in: header
          required: true
          schema: { type: string }
          description: Reference/Idempotency key for this request
        - name: x-ais-channel
          in: header
          required: true
          schema: { type: string }
        - name: content-language
          in: header
          required: false
          schema: { type: string }
          description: Preferred language for messages (e.g., "th", "en")
        - name: mw-user-id
          in: header
          schema: { type: string }
          example: 63e9eb9e733c3cc96dfe5027

        - name: mw-user-name
          in: header
          schema: { type: string }
          example: kanct571

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: object
                properties:
                  mobileNo:
                    type: string
                    example: '0829921384'
                  simSerial:
                    type: string
                    example: '2430004100504'
                  taxId:
                    type: string
                    example: '678123421111401'
          text/csv:
            schema:
              type: string
              format: binary
            examples:
              example1:
                summary: Example CSV Input
                value: |
                  mobileNo,simSerial,taxId
                  0829921384,2430004100504,678123421111401
                  0829921385,2430004100505,678123421111402

      responses:
        '200':
          description: การร้องขอสำเร็จ
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mobileNo:
                      type: string
                      example: '0829921384'
                    simSerial:
                      type: string
                      example: '2430004100504'
                    taxId:
                      type: string
                      example: '678123421111401'
                    mobileStatus:
                      type: string
                      example: Terminate-Inprogress
                    code:
                      type: string
                      example: "20200"
                    message:
                      type: string
                      example: The requested operation now in progress.
            text/csv:
              schema:
                type: string
                format: binary
              examples:
                success:
                  summary: Example CSV Response
                  value: |
                    mobileNo,simSerial,taxId,mobileStatus,code,message
                    0829921384,2430004100504,678123421111401,Terminate-Inprogress,20200,The requested operation now in progress.
                    0829921385,2430004100505,678123421111402,Terminate-Inprogress,20200,The requested operation now in progress.
        '400':
          description: ข้อมูลไม่ถูกต้อง
        '401':
          description: ไม่มีสิทธิ์เข้าถึง (Unauthorized)
        '500':
          description: Internal server error
  /api/v2/project/{projectId}/connectivities/change-sim:
    post:
      summary: Change SIM Serial in bulk
      operationId: changeSimBulk
      tags:
        - Connectivities
      parameters:
        - name: projectId
          in: path
          required: true
          schema: { type: string }
          description: Project ID

        - name: x-ais-OrderRef
          in: header
          required: true
          schema: { type: string }
          description: Reference/Idempotency key for this request
        - name: x-ais-channel
          in: header
          required: true
          schema: { type: string }
        - name: content-language
          in: header
          required: false
          schema: { type: string }
          description: Preferred language for messages (e.g., "th", "en")
        - name: mw-user-id
          in: header
          schema: { type: string }
          example: 63e9eb9e733c3cc96dfe5027

        - name: mw-user-name
          in: header
          schema: { type: string }
          example: kanct571


      requestBody:
        required: true
        content:
          application/json:
            examples:
              jsonExample:
                summary: JSON array example
                value:
                  - mobileNo: "0829921384"
                    oldSimSerial: "2430004100504"
                    newSimSerial: "2430004100506"
                    taxId: "678123421111401"
          text/csv:
            schema:
              type: string
              description: |
                CSV with header: mobileNo,oldSimSerial,newSimSerial,taxId
                - At least one of mobileNo or oldSimSerial must be present per row
                - taxId is required per row when x-ais-channel != MILKYWAY_WEB
            examples:
              csvExample:
                summary: CSV example
                value: |
                  mobileNo,oldSimSerial,newSimSerial,taxId
                  0829921384,2430004100504,2430004100506,678123421111401
                  0829921401,,2430004100507,2430004100505,678123421111401

      responses:
        '200':
          description: การร้องขอสำเร็จ
          content:
            application/json:
              schema:
               type: array
               items:
                  type: object
                  properties:
                    mobileNo:
                      type: string
                      example: '0829921384'
                    oldSimSerial:
                      type: string
                      example: '2430004100504'
                    newSimSerial:
                      type: string
                      example: '2430004100506'
                    taxId:
                      type: string
                      example: '678123421111401'
                    code:
                      type: string
                      example: "20200"
                    message:
                      type: string
                      example: The requested operation now in progress.
            text/csv:
              schema:
                type: string
                description: CSV result with appended 
              examples:
                successCsv:
                  value: |
                    mobileNo,oldSimSerial,newSimSerial,taxId,status,resultCode,message,orderNo
                    0829921384,2430004100504,2430004100506,678123421111401,SUCCESS,20000,Changed successfully,SO-20250814-000123
                     0829921384,2430004100504,2430004100505,678123421111401,SUCCESS,20000,Changed successfully,SO-20250814-000123

        '400':
          description: Invalid request body or CSV format / missing mandatory fields
          content:
            application/json:
              examples:
                invalidCsv:
                  value: { resultCode: "40300", message: "Invalid CSV: missing required header(s): newSimSerial" }
                invalidJson:
                  value: { resultCode: "40300", message: "items[0]: must contain at least one of mobileNo or oldSimSerial" }

        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                unauthorized:
                  value: { resultCode: "40101", message: "Access denied" }

        '403':
          description: Forbidden / Channel not allowed / parameter conflict
          content:
            application/json:
              examples:
                conflict:
                  value: { resultCode: "40301", message: "New SIM already in use by another number" }

        '404':
          description: Not Found
          content:
            application/json:
              examples:
                notFound:
                  value: { resultCode: "40401", message: "Data not found" }

        '500':
          description: Internal Server Error / Upstream error
          content:
            application/json:
              examples:
                systemError:
                  value: { resultCode: "50000", message: "System error" }
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: >
        The Client Credentials grant type is used by clients to obtain an access token outside of the context of a user.
      flows:
        clientCredentials:
          tokenUrl: http://10.138.37.218:31351/connect/token
          scopes: {}
    Bearer:
      type: apiKey
      description: >
        JWT Authorization header using the Bearer scheme.xq

        Enter 'Bearer' [space] and then your token in the text input below.

        Example: "Bearer 12345abcdef"
      name: Authorization
      in: header
  schemas:
    Schema:
      type: object
      properties:
        id:
          type: integer
          format: int64
